#!/usr/bin/env python
from utils.scons_hints import *

# Import the environment from parent
Import('env')

# Clone the environment to avoid modifying the global one
env = env.Clone(LIBS=["SwiftLibrary"])

# Configure C++ standard and optimizations
env.Append(CXXFLAGS=['-std=c++17'])

# Link everything together
program = env.Program('cpp_calls_swift', ["main.cpp"])

# Return the built targets
Return('program')
