#!/usr/bin/env python
from utils.scons_hints import *

# Import the environment from parent
Import('env')

# Clone the environment to avoid modifying the global one
env = env.Clone(LIBPATH=["#examples/cpp_library"], LIBS="cpp_library")
env["SWIFT_CXX_INTEROP"] = True
env.Append(SWIFTPATH=["#examples/cpp_library"]) # For module.modulemap

env.Append(SWIFTEXEFLAGS=[
    '-parse-as-library',
    '-Xcc', '-std=c++17',  # Pass C++ standard to Clang
])

program = env.SwiftProgram("swift_calls_cpp", ["main.swift"])

# Return the built targets
Return('program')
