#!/usr/bin/env python
from utils.scons_hints import *

# Import the environment from parent
Import('env')

# Clone the environment to avoid modifying the global one
env = env.Clone()

env["SWIFTMODULENAME"] = "SwiftLibrary"
env["SWIFT_CXX_INTEROP"] = True
env["SWIFT_EMIT_CXX_HEADER"] = True
env["SWIFT_CXX_HEADER_NAME"] = "SwiftLibrary-Swift.h"
swift_module = env.SwiftModule('SwiftLibrary', source=['point.swift', "calculator.swift"])

lib = env.StaticLibrary("SwiftLibrary", ["point.o", "calculator.o"])
